name: 'Update PR Triage Board'

on:
  schedule:
    - cron: '0 6 * * *'  # Run every day at 06:00
  workflow_dispatch:

jobs:
  pr-triage:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Triage Board
        uses: accordproject/pr-triage-board-bot@main
        with:
          organization: 'accordproject'
          project-number: '29'
          gh-app-id: '2856902'
          gh-app-installation-id: '109864494'
          gh-app-private-key: ${{ secrets.PR_BOT_APP_PRIVATE_KEY }}